# fly.toml app configuration file generated for photoit-quiet-fog-1658 on 2025-02-11T23:36:29-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'photoit-quiet-fog-1658'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
